### ISSUE TITLE
Asterisk before lemma on a main scholion urn:cite:hmt:msA.242v

### ISSUE THREAD

**Issue by mwauke** [hmteditors/hc-il18#15]
The first main scholion on 242v has an asterisk before the lemma. How should this be marked?

urn:cts:greekLit:tlg5026.msA.hmt:18.65

**Comment by brclar15** [comment]
A similar but different mark appears after the lemma of urn:cts:greekLit:tlg5026.msA.hmt:18.75
on folio urn:cite:hmt:msA.243r

see urn:cite:hmt:vaimg.VA243RN-0414@0.8,0.1788,0.023,0.0143

**Comment by brclar15** [comment]
there is a mark at the start of this scholion that almost resembles half of a start of scholion mark. Stephanie say's its an obelos. How do we deal with this?

urn:cite:hmt:vaimg.VA246VN-0748@0.218,0.2299,0.243,0.0563

urn:cts:greekLit:tlg5026.msA:hm:18.128

**Comment by arsimr16** [comment]
This has now been edited and indexed properly.
