### ISSUE TITLE
two mistakes on one word

### ISSUE THREAD

**Issue by cjschu17** [hmteditors/hc-il18#18]
urn:cite:hmt:vaimg.VA246RN-0417@0.673,0.7258,0.053,0.0218

On the last main scholia on 246r, there seems to be a word with two corrected accents.

**Comment by StephanieML** [comment]
what are you asking?

**Comment by brclar15** [comment]
I think they're asking how we deal with that in the XML.

**Comment by StephanieML** [comment]
the sic can have both mistakes and the corr can be the corrected version
