### ISSUE TITLE
out of place line with scholion

### ISSUE THREAD

**Issue by brclar15** [hmteditors/hc-il18#19]
At the top margin of the folio there is a line added in with a sign indicating where it belongs in the main text.  It is set off by hooked lines.  There is also a scholion next to the line.  How should we index and edit this?

urn:cite:hmt:vaimg.VA246VN-0748@0.386,0.1059,0.455,0.0639

**Comment by brclar15** [comment]
Erbse treats it as an Intermarginal, and does not include the line in the comment, as they don't appear to be closely connected. Dindorff, however, appears to treat it as a main scholion AND puts the line in the comment.

For now, we have treated it as a main scholion, following the advice of Stephanie. 
We have also indexed the line and edited it as a main text line.

**Comment by StephanieML** [comment]
In this case the line is marked with a connecting sign to tie it to the main text, however it is also marked with the backwards 'c's that tend to indicate that someone doesn't like the reading. It does have a scholion associated with it, so it definitely needs to be catalogued with scholia, but the reinserted line is definitely written in a main text hand, so I believe this is one of the cases where we should have the content in two places.

**Comment by StephanieML** [comment]
I think if we had no connecting sign and it wasn't in the main text hand we would exclusively call it a scholion. If it had no additional comment we would exclusively put it with main text. This is one of our "in the middle" cases.

**Comment by brclar15** [comment]
we've dealt with this as detailed above
