### ISSUE TITLE
Possible other category for Validation

### ISSUE THREAD

**Issue by brclar15** [hmteditors/hc-il18#20]
urn:cts:greekLit:tlg5026.msAil.hmt:18.6

the εω are not passing in MOM, as you would expect. They are meant to be substituted for the ης in αρῆς, making it αρεω. We don't really think that we should wrap the entire interlinear scholion in a sic element, but it also doesn't quite seem like they belong in an rs element with a "waw" atrribute. Is there another way to deal with this?

urn:cite:hmt:vaimg.VA240VN-0742@0.7,0.6679,0.069,0.0361

on urn:cite:hmt:msA.240v

**Comment by StephanieML** [comment]
I would call it waw

**Comment by StephanieML** [comment]
it's a string of non-parsable characters and our references cite it to the word it's offering an alternate for.

**Comment by brclar15** [comment]
im down for making it waw

**Comment by StephanieML** [comment]
make it so!
