### ISSUE TITLE
Indexing "τελος" and "Ομηρος" on 251r

### ISSUE THREAD

**Issue by cshanley18** [hmteditors/hc-il18#25]
urn:cite:hmt:vaimg.VA251RN-0422@0.179,0.4906,0.406,0.0323

How should we index the two words that appear beneath the book subscription?  Neither one seems to fit in any category of scholia.

**Comment by StephanieML** [comment]
Check the archive (probably the in progress branch) to see if we recorded them with the subscriptions; if not record them as scholia

**Comment by brclar15** [comment]
ah good call. They were edited when you and I did the book subscriptions, so we're allll set

**Comment by StephanieML** [comment]
yaaaaaaaayyyyyyy
