### ISSUE TITLE
Need help indexing 248v

### ISSUE THREAD

**Issue by brclar15** [hmteditors/hc-il18#27]
urn:cite:hmt:msA.248v

This folio is veryyy dense. We've indexed and edited all of the text on this folio EXCEPT for the text on the exterior of the page. Going off of just the visual, the top one looks like an exterior, but the other three do not. Here's an image ref
urn:cite:hmt:vaimg.VA248VN-0750@0.13,0.4177,0.134,0.3088

The bottom three are paired with dingbat footnote markers, and link up to places on the interior of the page. Here's another image ref!
urn:cite:hmt:vaimg.VA248VN-0750@0.84,0.5334,0.118,0.1645

Personally, I'd be down for calling them all interior. The scribe _wanted_ to make them interior scholia, but didn't have enough room due to the density of the scholia on the page.
However, my theory gets a little wonky when you look at the last footnote connector, as it is more interlinear...... But, would a comment of that length belong in the interlinear scholia?

Could we get some help please from the project manager and the editors/architects?

**Comment by brclar15** [comment]
After consulting with Professor Ebbott, we think we could make it a new scholia category, similar to the exterior-long on the first folio of book 12, urn:cite:hmt:msA.145v
We could make it exterior-linked, or something like that, to show that its not an exterior, but part of a different scholia group

**Comment by StephanieML** [comment]
Yes, we need to address the exterior long category. I'll talk with Prof. Smith and Casey when I get the chance.

**Comment by brclar15** [comment]
:+1:

**Comment by brclar15** [comment]
Have we had any more discussion or a decision on this issue?

**Comment by neelsmith** [comment]
We should make a new scholion document with URN urn:cts:greekLit:tlg5026.msAext_long:

We need to go back through earlier books and reclassify scholia.  That's a separate task, not for Il. 18 group necessarily.

**Comment by brclar15** [comment]
we have resolved this issue. The dingbats are linking the scholia to the interior section. The first scholion in the section is a true exterior. we'll edit and index these as such.
