### ISSUE TITLE
Mistagged PersName in Scholion 142: 

### ISSUE THREAD

**Issue by cshanley18** [hmteditors/hc-il18#28]
urn:cite:hmt:msA.247r

We have Proteus tagged as the god of the sea in Scholion 142, but we think this particular scholion refers to some other Proteus aside from the divinity.

**Comment by StephanieML** [comment]
give me the full scholion urn, and do you have any guess about who this Proteus is?

**Comment by brclar15** [comment]
urn:cts:greekLit:tlg5026.msA.hmt:18.142

not at all. Google-ing returns two Proteuseses - the shapshifting sea god, and the king of Egypt. neither seem to fit at all. Id love to tag him as a random grammarian, in parrallel to Philoxenos, but I havent found any Proteus who fits that description

**Comment by StephanieML** [comment]
after some intense googling, Proteas of Zeugma (or Proteas Zeugmatites) is a grammarian; you can see him at the end of this other article (beginning of the next one), but I can't find HW Miller's full article on him: http://www.jstor.org/stable/263955?seq=3#page_scan_tab_contents

**Comment by brclar15** [comment]
yay, this has been resolved!
