### ISSUE TITLE
239r: Deleted lemma/ scholion

### ISSUE THREAD

**Issue by scnevi17** [hmteditors/hc-il18#5]
The lemma and the first word of the scholion are written on the left of the page and indicated to be deletions (due to lack of space?) and then rewritten on the right side of the page with the rest of the comment. We are uncertain if it should be indexed and edited as its one or two scholia.

urn:cite:hmt:vaimg.VA239RN-0410@0.2,0.1773,0.62,0.0563

**Comment by StephanieML** [comment]
Just looked at it with Brian. I think we will probably want to go with two distinct scholia.

**Comment by brclar15** [comment]
Professor Smith suggested we edit it as a single scholion, and we've done that for now, unless the editors want to meet to discuss this issue as well.
